[33m5526d71[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m, [m[1;31morigin/master[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m)[m aanpassingen
A	LICENSE
A	README.md
A	avatar/avater.jpg
A	avatar/karatepunt.jpg
A	avatar/kin.jpg
A	avatar/kruin.jpg
A	avatar/logo-avatar.jpg
A	avatar/onder-arm.jpg
A	avatar/onder-neus.jpg
A	avatar/onder-oog.jpg
A	avatar/sleutelbeen.jpg
A	avatar/uitleg-eft.mp4
A	avatar/wenkbrauw.jpg
A	avatar/zijkant-oog.jpg
A	disclaimer.html
A	eft-tapping.html
A	eindpagina.html
A	extra-hulp.html
A	icons/icon-128x128.png
A	icons/icon-144x144.png
A	icons/icon-152x152.png
A	icons/icon-16x16.png
A	icons/icon-192x192.png
A	icons/icon-32x32.png
A	icons/icon-384x384.png
A	icons/icon-48x48.png
A	icons/icon-512x512.png
A	icons/icon-72x72.png
A	icons/icon-96x96.png
A	index.html
A	install-app.html
A	kloppunten.html
A	kloppunten/kloppunt-karatepunt.html
A	kloppunten/kloppunt-kin.html
A	kloppunten/kloppunt-kruin.html
A	kloppunten/kloppunt-neus.html
A	kloppunten/kloppunt-onder-arm.html
A	kloppunten/kloppunt-onder-neus.html
A	kloppunten/kloppunt-onder-oog.html
A	kloppunten/kloppunt-sleutelbeen.html
A	kloppunten/kloppunt-wenkbrauw.html
A	kloppunten/kloppunt-zijkant-oog.html
A	logo/favicon.jpg
A	logo/logo-app.jpg
A	logo/logo-avatar-zonderbg.png
A	logo/logo-website.jpg
A	logo/logo-website.png
A	manifest.json
A	robots.txt
A	sitemap.html.xml
A	styles.css
A	sw.js
A	wat-is-eft.html
